/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RestablecerContrasenaRouteImport } from './routes/restablecer-contrasena'
import { Route as ResonanciaRouteImport } from './routes/resonancia'
import { Route as RecuperarContrasenaRouteImport } from './routes/recuperar-contrasena'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as AppTareasIndexRouteImport } from './routes/_app.tareas.index'
import { Route as AppRevisionIaIndexRouteImport } from './routes/_app.revision-ia.index'
import { Route as AppReportesIndexRouteImport } from './routes/_app.reportes.index'
import { Route as AppPlantillasIndexRouteImport } from './routes/_app.plantillas.index'
import { Route as AppPagosIndexRouteImport } from './routes/_app.pagos.index'
import { Route as AppImportacionesIndexRouteImport } from './routes/_app.importaciones.index'
import { Route as AppDocumentosIndexRouteImport } from './routes/_app.documentos.index'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app.configuracion.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppCasosIndexRouteImport } from './routes/_app.casos.index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app.agenda.index'
import { Route as ApiGoogleDriveWebhookRouteImport } from './routes/api.google-drive.webhook'
import { Route as ApiGoogleDriveSyncDocumentRouteImport } from './routes/api.google-drive.sync-document'
import { Route as ApiGoogleDriveSyncClientRouteImport } from './routes/api.google-drive.sync-client'
import { Route as ApiGoogleDriveStatusRouteImport } from './routes/api.google-drive.status'
import { Route as ApiGoogleDriveRootFolderRouteImport } from './routes/api.google-drive.root-folder'
import { Route as ApiGoogleDrivePrepareDocumentTrashRouteImport } from './routes/api.google-drive.prepare-document-trash'
import { Route as ApiGoogleDriveMaintenanceRouteImport } from './routes/api.google-drive.maintenance'
import { Route as ApiGoogleDriveFoldersRouteImport } from './routes/api.google-drive.folders'
import { Route as ApiGoogleDriveDisconnectRouteImport } from './routes/api.google-drive.disconnect'
import { Route as ApiGoogleDriveConnectRouteImport } from './routes/api.google-drive.connect'
import { Route as ApiGoogleDriveCallbackRouteImport } from './routes/api.google-drive.callback'
import { Route as ApiGoogleCalendarWebhookRouteImport } from './routes/api.google-calendar.webhook'
import { Route as ApiGoogleCalendarSyncEventRouteImport } from './routes/api.google-calendar.sync-event'
import { Route as ApiGoogleCalendarStatusRouteImport } from './routes/api.google-calendar.status'
import { Route as ApiGoogleCalendarMaintenanceRouteImport } from './routes/api.google-calendar.maintenance'
import { Route as ApiGoogleCalendarConnectRouteImport } from './routes/api.google-calendar.connect'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api.google-calendar.callback'
import { Route as ApiGoogleCalendarActionsRouteImport } from './routes/api.google-calendar.actions'
import { Route as ApiEmailTestRouteImport } from './routes/api.email.test'
import { Route as ApiEmailStatusRouteImport } from './routes/api.email.status'
import { Route as ApiEmailSendReportRouteImport } from './routes/api.email.send-report'
import { Route as AppTareasTodasRouteImport } from './routes/_app.tareas.todas'
import { Route as AppTareasTableroRouteImport } from './routes/_app.tareas.tablero'
import { Route as AppTareasProximasRouteImport } from './routes/_app.tareas.proximas'
import { Route as AppTareasMiasRouteImport } from './routes/_app.tareas.mias'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes.$id'
import { Route as AppCasosIdRouteImport } from './routes/_app.casos.$id'
import { Route as ApiGoogleDriveOnboardingPreviewRouteImport } from './routes/api.google-drive.onboarding.preview'
import { Route as ApiGoogleDriveOnboardingApplyRouteImport } from './routes/api.google-drive.onboarding.apply'
import { Route as AppClientesIdTareasRouteImport } from './routes/_app.clientes.$id_.tareas'
import { Route as AppClientesIdReportesRouteImport } from './routes/_app.clientes.$id_.reportes'
import { Route as AppClientesIdExpedientesRouteImport } from './routes/_app.clientes.$id_.expedientes'
import { Route as AppClientesIdDocumentosRouteImport } from './routes/_app.clientes.$id_.documentos'

const RestablecerContrasenaRoute = RestablecerContrasenaRouteImport.update({
  id: '/restablecer-contrasena',
  path: '/restablecer-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const ResonanciaRoute = ResonanciaRouteImport.update({
  id: '/resonancia',
  path: '/resonancia',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarContrasenaRoute = RecuperarContrasenaRouteImport.update({
  id: '/recuperar-contrasena',
  path: '/recuperar-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTareasIndexRoute = AppTareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionIaIndexRoute = AppRevisionIaIndexRouteImport.update({
  id: '/revision-ia/',
  path: '/revision-ia/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesIndexRoute = AppReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlantillasIndexRoute = AppPlantillasIndexRouteImport.update({
  id: '/plantillas/',
  path: '/plantillas/',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosIndexRoute = AppPagosIndexRouteImport.update({
  id: '/pagos/',
  path: '/pagos/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacionesIndexRoute = AppImportacionesIndexRouteImport.update({
  id: '/importaciones/',
  path: '/importaciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosIndexRoute = AppDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIndexRoute = AppCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const ApiGoogleDriveWebhookRoute = ApiGoogleDriveWebhookRouteImport.update({
  id: '/api/google-drive/webhook',
  path: '/api/google-drive/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleDriveSyncDocumentRoute =
  ApiGoogleDriveSyncDocumentRouteImport.update({
    id: '/api/google-drive/sync-document',
    path: '/api/google-drive/sync-document',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveSyncClientRoute =
  ApiGoogleDriveSyncClientRouteImport.update({
    id: '/api/google-drive/sync-client',
    path: '/api/google-drive/sync-client',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveStatusRoute = ApiGoogleDriveStatusRouteImport.update({
  id: '/api/google-drive/status',
  path: '/api/google-drive/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleDriveRootFolderRoute =
  ApiGoogleDriveRootFolderRouteImport.update({
    id: '/api/google-drive/root-folder',
    path: '/api/google-drive/root-folder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDrivePrepareDocumentTrashRoute =
  ApiGoogleDrivePrepareDocumentTrashRouteImport.update({
    id: '/api/google-drive/prepare-document-trash',
    path: '/api/google-drive/prepare-document-trash',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveMaintenanceRoute =
  ApiGoogleDriveMaintenanceRouteImport.update({
    id: '/api/google-drive/maintenance',
    path: '/api/google-drive/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveFoldersRoute = ApiGoogleDriveFoldersRouteImport.update({
  id: '/api/google-drive/folders',
  path: '/api/google-drive/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleDriveDisconnectRoute =
  ApiGoogleDriveDisconnectRouteImport.update({
    id: '/api/google-drive/disconnect',
    path: '/api/google-drive/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveConnectRoute = ApiGoogleDriveConnectRouteImport.update({
  id: '/api/google-drive/connect',
  path: '/api/google-drive/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleDriveCallbackRoute = ApiGoogleDriveCallbackRouteImport.update({
  id: '/api/google-drive/callback',
  path: '/api/google-drive/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarWebhookRoute =
  ApiGoogleCalendarWebhookRouteImport.update({
    id: '/api/google-calendar/webhook',
    path: '/api/google-calendar/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarSyncEventRoute =
  ApiGoogleCalendarSyncEventRouteImport.update({
    id: '/api/google-calendar/sync-event',
    path: '/api/google-calendar/sync-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarStatusRoute = ApiGoogleCalendarStatusRouteImport.update({
  id: '/api/google-calendar/status',
  path: '/api/google-calendar/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarMaintenanceRoute =
  ApiGoogleCalendarMaintenanceRouteImport.update({
    id: '/api/google-calendar/maintenance',
    path: '/api/google-calendar/maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarConnectRoute =
  ApiGoogleCalendarConnectRouteImport.update({
    id: '/api/google-calendar/connect',
    path: '/api/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarActionsRoute =
  ApiGoogleCalendarActionsRouteImport.update({
    id: '/api/google-calendar/actions',
    path: '/api/google-calendar/actions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiEmailTestRoute = ApiEmailTestRouteImport.update({
  id: '/api/email/test',
  path: '/api/email/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailStatusRoute = ApiEmailStatusRouteImport.update({
  id: '/api/email/status',
  path: '/api/email/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailSendReportRoute = ApiEmailSendReportRouteImport.update({
  id: '/api/email/send-report',
  path: '/api/email/send-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTareasTodasRoute = AppTareasTodasRouteImport.update({
  id: '/tareas/todas',
  path: '/tareas/todas',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasTableroRoute = AppTareasTableroRouteImport.update({
  id: '/tareas/tablero',
  path: '/tareas/tablero',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasProximasRoute = AppTareasProximasRouteImport.update({
  id: '/tareas/proximas',
  path: '/tareas/proximas',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasMiasRoute = AppTareasMiasRouteImport.update({
  id: '/tareas/mias',
  path: '/tareas/mias',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIdRoute = AppCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiGoogleDriveOnboardingPreviewRoute =
  ApiGoogleDriveOnboardingPreviewRouteImport.update({
    id: '/api/google-drive/onboarding/preview',
    path: '/api/google-drive/onboarding/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleDriveOnboardingApplyRoute =
  ApiGoogleDriveOnboardingApplyRouteImport.update({
    id: '/api/google-drive/onboarding/apply',
    path: '/api/google-drive/onboarding/apply',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppClientesIdTareasRoute = AppClientesIdTareasRouteImport.update({
  id: '/clientes/$id_/tareas',
  path: '/clientes/$id/tareas',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdReportesRoute = AppClientesIdReportesRouteImport.update({
  id: '/clientes/$id_/reportes',
  path: '/clientes/$id/reportes',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdExpedientesRoute =
  AppClientesIdExpedientesRouteImport.update({
    id: '/clientes/$id_/expedientes',
    path: '/clientes/$id/expedientes',
    getParentRoute: () => AppRoute,
  } as any)
const AppClientesIdDocumentosRoute = AppClientesIdDocumentosRouteImport.update({
  id: '/clientes/$id_/documentos',
  path: '/clientes/$id/documentos',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/resonancia': typeof ResonanciaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/api/health': typeof ApiHealthRoute
  '/casos/$id': typeof AppCasosIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/tareas/mias': typeof AppTareasMiasRoute
  '/tareas/proximas': typeof AppTareasProximasRoute
  '/tareas/tablero': typeof AppTareasTableroRoute
  '/tareas/todas': typeof AppTareasTodasRoute
  '/api/email/send-report': typeof ApiEmailSendReportRoute
  '/api/email/status': typeof ApiEmailStatusRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/maintenance': typeof ApiGoogleCalendarMaintenanceRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/api/google-drive/callback': typeof ApiGoogleDriveCallbackRoute
  '/api/google-drive/connect': typeof ApiGoogleDriveConnectRoute
  '/api/google-drive/disconnect': typeof ApiGoogleDriveDisconnectRoute
  '/api/google-drive/folders': typeof ApiGoogleDriveFoldersRoute
  '/api/google-drive/maintenance': typeof ApiGoogleDriveMaintenanceRoute
  '/api/google-drive/prepare-document-trash': typeof ApiGoogleDrivePrepareDocumentTrashRoute
  '/api/google-drive/root-folder': typeof ApiGoogleDriveRootFolderRoute
  '/api/google-drive/status': typeof ApiGoogleDriveStatusRoute
  '/api/google-drive/sync-client': typeof ApiGoogleDriveSyncClientRoute
  '/api/google-drive/sync-document': typeof ApiGoogleDriveSyncDocumentRoute
  '/api/google-drive/webhook': typeof ApiGoogleDriveWebhookRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/casos/': typeof AppCasosIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
  '/documentos/': typeof AppDocumentosIndexRoute
  '/importaciones/': typeof AppImportacionesIndexRoute
  '/pagos/': typeof AppPagosIndexRoute
  '/plantillas/': typeof AppPlantillasIndexRoute
  '/reportes/': typeof AppReportesIndexRoute
  '/revision-ia/': typeof AppRevisionIaIndexRoute
  '/tareas/': typeof AppTareasIndexRoute
  '/clientes/$id/documentos': typeof AppClientesIdDocumentosRoute
  '/clientes/$id/expedientes': typeof AppClientesIdExpedientesRoute
  '/clientes/$id/reportes': typeof AppClientesIdReportesRoute
  '/clientes/$id/tareas': typeof AppClientesIdTareasRoute
  '/api/google-drive/onboarding/apply': typeof ApiGoogleDriveOnboardingApplyRoute
  '/api/google-drive/onboarding/preview': typeof ApiGoogleDriveOnboardingPreviewRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/resonancia': typeof ResonanciaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/api/health': typeof ApiHealthRoute
  '/': typeof AppIndexRoute
  '/casos/$id': typeof AppCasosIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/tareas/mias': typeof AppTareasMiasRoute
  '/tareas/proximas': typeof AppTareasProximasRoute
  '/tareas/tablero': typeof AppTareasTableroRoute
  '/tareas/todas': typeof AppTareasTodasRoute
  '/api/email/send-report': typeof ApiEmailSendReportRoute
  '/api/email/status': typeof ApiEmailStatusRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/maintenance': typeof ApiGoogleCalendarMaintenanceRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/api/google-drive/callback': typeof ApiGoogleDriveCallbackRoute
  '/api/google-drive/connect': typeof ApiGoogleDriveConnectRoute
  '/api/google-drive/disconnect': typeof ApiGoogleDriveDisconnectRoute
  '/api/google-drive/folders': typeof ApiGoogleDriveFoldersRoute
  '/api/google-drive/maintenance': typeof ApiGoogleDriveMaintenanceRoute
  '/api/google-drive/prepare-document-trash': typeof ApiGoogleDrivePrepareDocumentTrashRoute
  '/api/google-drive/root-folder': typeof ApiGoogleDriveRootFolderRoute
  '/api/google-drive/status': typeof ApiGoogleDriveStatusRoute
  '/api/google-drive/sync-client': typeof ApiGoogleDriveSyncClientRoute
  '/api/google-drive/sync-document': typeof ApiGoogleDriveSyncDocumentRoute
  '/api/google-drive/webhook': typeof ApiGoogleDriveWebhookRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/casos': typeof AppCasosIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
  '/documentos': typeof AppDocumentosIndexRoute
  '/importaciones': typeof AppImportacionesIndexRoute
  '/pagos': typeof AppPagosIndexRoute
  '/plantillas': typeof AppPlantillasIndexRoute
  '/reportes': typeof AppReportesIndexRoute
  '/revision-ia': typeof AppRevisionIaIndexRoute
  '/tareas': typeof AppTareasIndexRoute
  '/clientes/$id/documentos': typeof AppClientesIdDocumentosRoute
  '/clientes/$id/expedientes': typeof AppClientesIdExpedientesRoute
  '/clientes/$id/reportes': typeof AppClientesIdReportesRoute
  '/clientes/$id/tareas': typeof AppClientesIdTareasRoute
  '/api/google-drive/onboarding/apply': typeof ApiGoogleDriveOnboardingApplyRoute
  '/api/google-drive/onboarding/preview': typeof ApiGoogleDriveOnboardingPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/recuperar-contrasena': typeof RecuperarContrasenaRoute
  '/resonancia': typeof ResonanciaRoute
  '/restablecer-contrasena': typeof RestablecerContrasenaRoute
  '/api/health': typeof ApiHealthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/casos/$id': typeof AppCasosIdRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/tareas/mias': typeof AppTareasMiasRoute
  '/_app/tareas/proximas': typeof AppTareasProximasRoute
  '/_app/tareas/tablero': typeof AppTareasTableroRoute
  '/_app/tareas/todas': typeof AppTareasTodasRoute
  '/api/email/send-report': typeof ApiEmailSendReportRoute
  '/api/email/status': typeof ApiEmailStatusRoute
  '/api/email/test': typeof ApiEmailTestRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/maintenance': typeof ApiGoogleCalendarMaintenanceRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/api/google-drive/callback': typeof ApiGoogleDriveCallbackRoute
  '/api/google-drive/connect': typeof ApiGoogleDriveConnectRoute
  '/api/google-drive/disconnect': typeof ApiGoogleDriveDisconnectRoute
  '/api/google-drive/folders': typeof ApiGoogleDriveFoldersRoute
  '/api/google-drive/maintenance': typeof ApiGoogleDriveMaintenanceRoute
  '/api/google-drive/prepare-document-trash': typeof ApiGoogleDrivePrepareDocumentTrashRoute
  '/api/google-drive/root-folder': typeof ApiGoogleDriveRootFolderRoute
  '/api/google-drive/status': typeof ApiGoogleDriveStatusRoute
  '/api/google-drive/sync-client': typeof ApiGoogleDriveSyncClientRoute
  '/api/google-drive/sync-document': typeof ApiGoogleDriveSyncDocumentRoute
  '/api/google-drive/webhook': typeof ApiGoogleDriveWebhookRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/casos/': typeof AppCasosIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
  '/_app/documentos/': typeof AppDocumentosIndexRoute
  '/_app/importaciones/': typeof AppImportacionesIndexRoute
  '/_app/pagos/': typeof AppPagosIndexRoute
  '/_app/plantillas/': typeof AppPlantillasIndexRoute
  '/_app/reportes/': typeof AppReportesIndexRoute
  '/_app/revision-ia/': typeof AppRevisionIaIndexRoute
  '/_app/tareas/': typeof AppTareasIndexRoute
  '/_app/clientes/$id_/documentos': typeof AppClientesIdDocumentosRoute
  '/_app/clientes/$id_/expedientes': typeof AppClientesIdExpedientesRoute
  '/_app/clientes/$id_/reportes': typeof AppClientesIdReportesRoute
  '/_app/clientes/$id_/tareas': typeof AppClientesIdTareasRoute
  '/api/google-drive/onboarding/apply': typeof ApiGoogleDriveOnboardingApplyRoute
  '/api/google-drive/onboarding/preview': typeof ApiGoogleDriveOnboardingPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recuperar-contrasena'
    | '/resonancia'
    | '/restablecer-contrasena'
    | '/api/health'
    | '/casos/$id'
    | '/clientes/$id'
    | '/tareas/mias'
    | '/tareas/proximas'
    | '/tareas/tablero'
    | '/tareas/todas'
    | '/api/email/send-report'
    | '/api/email/status'
    | '/api/email/test'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/maintenance'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/api/google-drive/callback'
    | '/api/google-drive/connect'
    | '/api/google-drive/disconnect'
    | '/api/google-drive/folders'
    | '/api/google-drive/maintenance'
    | '/api/google-drive/prepare-document-trash'
    | '/api/google-drive/root-folder'
    | '/api/google-drive/status'
    | '/api/google-drive/sync-client'
    | '/api/google-drive/sync-document'
    | '/api/google-drive/webhook'
    | '/agenda/'
    | '/casos/'
    | '/clientes/'
    | '/configuracion/'
    | '/documentos/'
    | '/importaciones/'
    | '/pagos/'
    | '/plantillas/'
    | '/reportes/'
    | '/revision-ia/'
    | '/tareas/'
    | '/clientes/$id/documentos'
    | '/clientes/$id/expedientes'
    | '/clientes/$id/reportes'
    | '/clientes/$id/tareas'
    | '/api/google-drive/onboarding/apply'
    | '/api/google-drive/onboarding/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recuperar-contrasena'
    | '/resonancia'
    | '/restablecer-contrasena'
    | '/api/health'
    | '/'
    | '/casos/$id'
    | '/clientes/$id'
    | '/tareas/mias'
    | '/tareas/proximas'
    | '/tareas/tablero'
    | '/tareas/todas'
    | '/api/email/send-report'
    | '/api/email/status'
    | '/api/email/test'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/maintenance'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/api/google-drive/callback'
    | '/api/google-drive/connect'
    | '/api/google-drive/disconnect'
    | '/api/google-drive/folders'
    | '/api/google-drive/maintenance'
    | '/api/google-drive/prepare-document-trash'
    | '/api/google-drive/root-folder'
    | '/api/google-drive/status'
    | '/api/google-drive/sync-client'
    | '/api/google-drive/sync-document'
    | '/api/google-drive/webhook'
    | '/agenda'
    | '/casos'
    | '/clientes'
    | '/configuracion'
    | '/documentos'
    | '/importaciones'
    | '/pagos'
    | '/plantillas'
    | '/reportes'
    | '/revision-ia'
    | '/tareas'
    | '/clientes/$id/documentos'
    | '/clientes/$id/expedientes'
    | '/clientes/$id/reportes'
    | '/clientes/$id/tareas'
    | '/api/google-drive/onboarding/apply'
    | '/api/google-drive/onboarding/preview'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/recuperar-contrasena'
    | '/resonancia'
    | '/restablecer-contrasena'
    | '/api/health'
    | '/_app/'
    | '/_app/casos/$id'
    | '/_app/clientes/$id'
    | '/_app/tareas/mias'
    | '/_app/tareas/proximas'
    | '/_app/tareas/tablero'
    | '/_app/tareas/todas'
    | '/api/email/send-report'
    | '/api/email/status'
    | '/api/email/test'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/maintenance'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/api/google-drive/callback'
    | '/api/google-drive/connect'
    | '/api/google-drive/disconnect'
    | '/api/google-drive/folders'
    | '/api/google-drive/maintenance'
    | '/api/google-drive/prepare-document-trash'
    | '/api/google-drive/root-folder'
    | '/api/google-drive/status'
    | '/api/google-drive/sync-client'
    | '/api/google-drive/sync-document'
    | '/api/google-drive/webhook'
    | '/_app/agenda/'
    | '/_app/casos/'
    | '/_app/clientes/'
    | '/_app/configuracion/'
    | '/_app/documentos/'
    | '/_app/importaciones/'
    | '/_app/pagos/'
    | '/_app/plantillas/'
    | '/_app/reportes/'
    | '/_app/revision-ia/'
    | '/_app/tareas/'
    | '/_app/clientes/$id_/documentos'
    | '/_app/clientes/$id_/expedientes'
    | '/_app/clientes/$id_/reportes'
    | '/_app/clientes/$id_/tareas'
    | '/api/google-drive/onboarding/apply'
    | '/api/google-drive/onboarding/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecuperarContrasenaRoute: typeof RecuperarContrasenaRoute
  ResonanciaRoute: typeof ResonanciaRoute
  RestablecerContrasenaRoute: typeof RestablecerContrasenaRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiEmailSendReportRoute: typeof ApiEmailSendReportRoute
  ApiEmailStatusRoute: typeof ApiEmailStatusRoute
  ApiEmailTestRoute: typeof ApiEmailTestRoute
  ApiGoogleCalendarActionsRoute: typeof ApiGoogleCalendarActionsRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarConnectRoute: typeof ApiGoogleCalendarConnectRoute
  ApiGoogleCalendarMaintenanceRoute: typeof ApiGoogleCalendarMaintenanceRoute
  ApiGoogleCalendarStatusRoute: typeof ApiGoogleCalendarStatusRoute
  ApiGoogleCalendarSyncEventRoute: typeof ApiGoogleCalendarSyncEventRoute
  ApiGoogleCalendarWebhookRoute: typeof ApiGoogleCalendarWebhookRoute
  ApiGoogleDriveCallbackRoute: typeof ApiGoogleDriveCallbackRoute
  ApiGoogleDriveConnectRoute: typeof ApiGoogleDriveConnectRoute
  ApiGoogleDriveDisconnectRoute: typeof ApiGoogleDriveDisconnectRoute
  ApiGoogleDriveFoldersRoute: typeof ApiGoogleDriveFoldersRoute
  ApiGoogleDriveMaintenanceRoute: typeof ApiGoogleDriveMaintenanceRoute
  ApiGoogleDrivePrepareDocumentTrashRoute: typeof ApiGoogleDrivePrepareDocumentTrashRoute
  ApiGoogleDriveRootFolderRoute: typeof ApiGoogleDriveRootFolderRoute
  ApiGoogleDriveStatusRoute: typeof ApiGoogleDriveStatusRoute
  ApiGoogleDriveSyncClientRoute: typeof ApiGoogleDriveSyncClientRoute
  ApiGoogleDriveSyncDocumentRoute: typeof ApiGoogleDriveSyncDocumentRoute
  ApiGoogleDriveWebhookRoute: typeof ApiGoogleDriveWebhookRoute
  ApiGoogleDriveOnboardingApplyRoute: typeof ApiGoogleDriveOnboardingApplyRoute
  ApiGoogleDriveOnboardingPreviewRoute: typeof ApiGoogleDriveOnboardingPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/restablecer-contrasena': {
      id: '/restablecer-contrasena'
      path: '/restablecer-contrasena'
      fullPath: '/restablecer-contrasena'
      preLoaderRoute: typeof RestablecerContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resonancia': {
      id: '/resonancia'
      path: '/resonancia'
      fullPath: '/resonancia'
      preLoaderRoute: typeof ResonanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-contrasena': {
      id: '/recuperar-contrasena'
      path: '/recuperar-contrasena'
      fullPath: '/recuperar-contrasena'
      preLoaderRoute: typeof RecuperarContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tareas/': {
      id: '/_app/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof AppTareasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revision-ia/': {
      id: '/_app/revision-ia/'
      path: '/revision-ia'
      fullPath: '/revision-ia/'
      preLoaderRoute: typeof AppRevisionIaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes/': {
      id: '/_app/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AppReportesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plantillas/': {
      id: '/_app/plantillas/'
      path: '/plantillas'
      fullPath: '/plantillas/'
      preLoaderRoute: typeof AppPlantillasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos/': {
      id: '/_app/pagos/'
      path: '/pagos'
      fullPath: '/pagos/'
      preLoaderRoute: typeof AppPagosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importaciones/': {
      id: '/_app/importaciones/'
      path: '/importaciones'
      fullPath: '/importaciones/'
      preLoaderRoute: typeof AppImportacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos/': {
      id: '/_app/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AppDocumentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/configuracion'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casos/': {
      id: '/_app/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof AppCasosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/google-drive/webhook': {
      id: '/api/google-drive/webhook'
      path: '/api/google-drive/webhook'
      fullPath: '/api/google-drive/webhook'
      preLoaderRoute: typeof ApiGoogleDriveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/sync-document': {
      id: '/api/google-drive/sync-document'
      path: '/api/google-drive/sync-document'
      fullPath: '/api/google-drive/sync-document'
      preLoaderRoute: typeof ApiGoogleDriveSyncDocumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/sync-client': {
      id: '/api/google-drive/sync-client'
      path: '/api/google-drive/sync-client'
      fullPath: '/api/google-drive/sync-client'
      preLoaderRoute: typeof ApiGoogleDriveSyncClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/status': {
      id: '/api/google-drive/status'
      path: '/api/google-drive/status'
      fullPath: '/api/google-drive/status'
      preLoaderRoute: typeof ApiGoogleDriveStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/root-folder': {
      id: '/api/google-drive/root-folder'
      path: '/api/google-drive/root-folder'
      fullPath: '/api/google-drive/root-folder'
      preLoaderRoute: typeof ApiGoogleDriveRootFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/prepare-document-trash': {
      id: '/api/google-drive/prepare-document-trash'
      path: '/api/google-drive/prepare-document-trash'
      fullPath: '/api/google-drive/prepare-document-trash'
      preLoaderRoute: typeof ApiGoogleDrivePrepareDocumentTrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/maintenance': {
      id: '/api/google-drive/maintenance'
      path: '/api/google-drive/maintenance'
      fullPath: '/api/google-drive/maintenance'
      preLoaderRoute: typeof ApiGoogleDriveMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/folders': {
      id: '/api/google-drive/folders'
      path: '/api/google-drive/folders'
      fullPath: '/api/google-drive/folders'
      preLoaderRoute: typeof ApiGoogleDriveFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/disconnect': {
      id: '/api/google-drive/disconnect'
      path: '/api/google-drive/disconnect'
      fullPath: '/api/google-drive/disconnect'
      preLoaderRoute: typeof ApiGoogleDriveDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/connect': {
      id: '/api/google-drive/connect'
      path: '/api/google-drive/connect'
      fullPath: '/api/google-drive/connect'
      preLoaderRoute: typeof ApiGoogleDriveConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/callback': {
      id: '/api/google-drive/callback'
      path: '/api/google-drive/callback'
      fullPath: '/api/google-drive/callback'
      preLoaderRoute: typeof ApiGoogleDriveCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/webhook': {
      id: '/api/google-calendar/webhook'
      path: '/api/google-calendar/webhook'
      fullPath: '/api/google-calendar/webhook'
      preLoaderRoute: typeof ApiGoogleCalendarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/sync-event': {
      id: '/api/google-calendar/sync-event'
      path: '/api/google-calendar/sync-event'
      fullPath: '/api/google-calendar/sync-event'
      preLoaderRoute: typeof ApiGoogleCalendarSyncEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/status': {
      id: '/api/google-calendar/status'
      path: '/api/google-calendar/status'
      fullPath: '/api/google-calendar/status'
      preLoaderRoute: typeof ApiGoogleCalendarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/maintenance': {
      id: '/api/google-calendar/maintenance'
      path: '/api/google-calendar/maintenance'
      fullPath: '/api/google-calendar/maintenance'
      preLoaderRoute: typeof ApiGoogleCalendarMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/connect': {
      id: '/api/google-calendar/connect'
      path: '/api/google-calendar/connect'
      fullPath: '/api/google-calendar/connect'
      preLoaderRoute: typeof ApiGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/actions': {
      id: '/api/google-calendar/actions'
      path: '/api/google-calendar/actions'
      fullPath: '/api/google-calendar/actions'
      preLoaderRoute: typeof ApiGoogleCalendarActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/test': {
      id: '/api/email/test'
      path: '/api/email/test'
      fullPath: '/api/email/test'
      preLoaderRoute: typeof ApiEmailTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/status': {
      id: '/api/email/status'
      path: '/api/email/status'
      fullPath: '/api/email/status'
      preLoaderRoute: typeof ApiEmailStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email/send-report': {
      id: '/api/email/send-report'
      path: '/api/email/send-report'
      fullPath: '/api/email/send-report'
      preLoaderRoute: typeof ApiEmailSendReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tareas/todas': {
      id: '/_app/tareas/todas'
      path: '/tareas/todas'
      fullPath: '/tareas/todas'
      preLoaderRoute: typeof AppTareasTodasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/tablero': {
      id: '/_app/tareas/tablero'
      path: '/tareas/tablero'
      fullPath: '/tareas/tablero'
      preLoaderRoute: typeof AppTareasTableroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/proximas': {
      id: '/_app/tareas/proximas'
      path: '/tareas/proximas'
      fullPath: '/tareas/proximas'
      preLoaderRoute: typeof AppTareasProximasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/mias': {
      id: '/_app/tareas/mias'
      path: '/tareas/mias'
      fullPath: '/tareas/mias'
      preLoaderRoute: typeof AppTareasMiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casos/$id': {
      id: '/_app/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof AppCasosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/google-drive/onboarding/preview': {
      id: '/api/google-drive/onboarding/preview'
      path: '/api/google-drive/onboarding/preview'
      fullPath: '/api/google-drive/onboarding/preview'
      preLoaderRoute: typeof ApiGoogleDriveOnboardingPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-drive/onboarding/apply': {
      id: '/api/google-drive/onboarding/apply'
      path: '/api/google-drive/onboarding/apply'
      fullPath: '/api/google-drive/onboarding/apply'
      preLoaderRoute: typeof ApiGoogleDriveOnboardingApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/clientes/$id_/tareas': {
      id: '/_app/clientes/$id_/tareas'
      path: '/clientes/$id/tareas'
      fullPath: '/clientes/$id/tareas'
      preLoaderRoute: typeof AppClientesIdTareasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id_/reportes': {
      id: '/_app/clientes/$id_/reportes'
      path: '/clientes/$id/reportes'
      fullPath: '/clientes/$id/reportes'
      preLoaderRoute: typeof AppClientesIdReportesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id_/expedientes': {
      id: '/_app/clientes/$id_/expedientes'
      path: '/clientes/$id/expedientes'
      fullPath: '/clientes/$id/expedientes'
      preLoaderRoute: typeof AppClientesIdExpedientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id_/documentos': {
      id: '/_app/clientes/$id_/documentos'
      path: '/clientes/$id/documentos'
      fullPath: '/clientes/$id/documentos'
      preLoaderRoute: typeof AppClientesIdDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCasosIdRoute: typeof AppCasosIdRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppTareasMiasRoute: typeof AppTareasMiasRoute
  AppTareasProximasRoute: typeof AppTareasProximasRoute
  AppTareasTableroRoute: typeof AppTareasTableroRoute
  AppTareasTodasRoute: typeof AppTareasTodasRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppCasosIndexRoute: typeof AppCasosIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
  AppDocumentosIndexRoute: typeof AppDocumentosIndexRoute
  AppImportacionesIndexRoute: typeof AppImportacionesIndexRoute
  AppPagosIndexRoute: typeof AppPagosIndexRoute
  AppPlantillasIndexRoute: typeof AppPlantillasIndexRoute
  AppReportesIndexRoute: typeof AppReportesIndexRoute
  AppRevisionIaIndexRoute: typeof AppRevisionIaIndexRoute
  AppTareasIndexRoute: typeof AppTareasIndexRoute
  AppClientesIdDocumentosRoute: typeof AppClientesIdDocumentosRoute
  AppClientesIdExpedientesRoute: typeof AppClientesIdExpedientesRoute
  AppClientesIdReportesRoute: typeof AppClientesIdReportesRoute
  AppClientesIdTareasRoute: typeof AppClientesIdTareasRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCasosIdRoute: AppCasosIdRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppTareasMiasRoute: AppTareasMiasRoute,
  AppTareasProximasRoute: AppTareasProximasRoute,
  AppTareasTableroRoute: AppTareasTableroRoute,
  AppTareasTodasRoute: AppTareasTodasRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppCasosIndexRoute: AppCasosIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
  AppDocumentosIndexRoute: AppDocumentosIndexRoute,
  AppImportacionesIndexRoute: AppImportacionesIndexRoute,
  AppPagosIndexRoute: AppPagosIndexRoute,
  AppPlantillasIndexRoute: AppPlantillasIndexRoute,
  AppReportesIndexRoute: AppReportesIndexRoute,
  AppRevisionIaIndexRoute: AppRevisionIaIndexRoute,
  AppTareasIndexRoute: AppTareasIndexRoute,
  AppClientesIdDocumentosRoute: AppClientesIdDocumentosRoute,
  AppClientesIdExpedientesRoute: AppClientesIdExpedientesRoute,
  AppClientesIdReportesRoute: AppClientesIdReportesRoute,
  AppClientesIdTareasRoute: AppClientesIdTareasRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RecuperarContrasenaRoute: RecuperarContrasenaRoute,
  ResonanciaRoute: ResonanciaRoute,
  RestablecerContrasenaRoute: RestablecerContrasenaRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiEmailSendReportRoute: ApiEmailSendReportRoute,
  ApiEmailStatusRoute: ApiEmailStatusRoute,
  ApiEmailTestRoute: ApiEmailTestRoute,
  ApiGoogleCalendarActionsRoute: ApiGoogleCalendarActionsRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarConnectRoute: ApiGoogleCalendarConnectRoute,
  ApiGoogleCalendarMaintenanceRoute: ApiGoogleCalendarMaintenanceRoute,
  ApiGoogleCalendarStatusRoute: ApiGoogleCalendarStatusRoute,
  ApiGoogleCalendarSyncEventRoute: ApiGoogleCalendarSyncEventRoute,
  ApiGoogleCalendarWebhookRoute: ApiGoogleCalendarWebhookRoute,
  ApiGoogleDriveCallbackRoute: ApiGoogleDriveCallbackRoute,
  ApiGoogleDriveConnectRoute: ApiGoogleDriveConnectRoute,
  ApiGoogleDriveDisconnectRoute: ApiGoogleDriveDisconnectRoute,
  ApiGoogleDriveFoldersRoute: ApiGoogleDriveFoldersRoute,
  ApiGoogleDriveMaintenanceRoute: ApiGoogleDriveMaintenanceRoute,
  ApiGoogleDrivePrepareDocumentTrashRoute:
    ApiGoogleDrivePrepareDocumentTrashRoute,
  ApiGoogleDriveRootFolderRoute: ApiGoogleDriveRootFolderRoute,
  ApiGoogleDriveStatusRoute: ApiGoogleDriveStatusRoute,
  ApiGoogleDriveSyncClientRoute: ApiGoogleDriveSyncClientRoute,
  ApiGoogleDriveSyncDocumentRoute: ApiGoogleDriveSyncDocumentRoute,
  ApiGoogleDriveWebhookRoute: ApiGoogleDriveWebhookRoute,
  ApiGoogleDriveOnboardingApplyRoute: ApiGoogleDriveOnboardingApplyRoute,
  ApiGoogleDriveOnboardingPreviewRoute: ApiGoogleDriveOnboardingPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
