/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResonanciaRouteImport } from './routes/resonancia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTareasIndexRouteImport } from './routes/_app.tareas.index'
import { Route as AppRevisionIaIndexRouteImport } from './routes/_app.revision-ia.index'
import { Route as AppReportesIndexRouteImport } from './routes/_app.reportes.index'
import { Route as AppPagosIndexRouteImport } from './routes/_app.pagos.index'
import { Route as AppImportacionesIndexRouteImport } from './routes/_app.importaciones.index'
import { Route as AppDocumentosIndexRouteImport } from './routes/_app.documentos.index'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app.configuracion.index'
import { Route as AppClientesIndexRouteImport } from './routes/_app.clientes.index'
import { Route as AppCasosIndexRouteImport } from './routes/_app.casos.index'
import { Route as AppAgendaIndexRouteImport } from './routes/_app.agenda.index'
import { Route as ApiGoogleCalendarWebhookRouteImport } from './routes/api.google-calendar.webhook'
import { Route as ApiGoogleCalendarSyncEventRouteImport } from './routes/api.google-calendar.sync-event'
import { Route as ApiGoogleCalendarStatusRouteImport } from './routes/api.google-calendar.status'
import { Route as ApiGoogleCalendarConnectRouteImport } from './routes/api.google-calendar.connect'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api.google-calendar.callback'
import { Route as ApiGoogleCalendarActionsRouteImport } from './routes/api.google-calendar.actions'
import { Route as AppTareasTodasRouteImport } from './routes/_app.tareas.todas'
import { Route as AppTareasTableroRouteImport } from './routes/_app.tareas.tablero'
import { Route as AppTareasProximasRouteImport } from './routes/_app.tareas.proximas'
import { Route as AppTareasMiasRouteImport } from './routes/_app.tareas.mias'
import { Route as AppClientesIdRouteImport } from './routes/_app.clientes.$id'
import { Route as AppCasosIdRouteImport } from './routes/_app.casos.$id'

const ResonanciaRoute = ResonanciaRouteImport.update({
  id: '/resonancia',
  path: '/resonancia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasIndexRoute = AppTareasIndexRouteImport.update({
  id: '/tareas/',
  path: '/tareas/',
  getParentRoute: () => AppRoute,
} as any)
const AppRevisionIaIndexRoute = AppRevisionIaIndexRouteImport.update({
  id: '/revision-ia/',
  path: '/revision-ia/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportesIndexRoute = AppReportesIndexRouteImport.update({
  id: '/reportes/',
  path: '/reportes/',
  getParentRoute: () => AppRoute,
} as any)
const AppPagosIndexRoute = AppPagosIndexRouteImport.update({
  id: '/pagos/',
  path: '/pagos/',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacionesIndexRoute = AppImportacionesIndexRouteImport.update({
  id: '/importaciones/',
  path: '/importaciones/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosIndexRoute = AppDocumentosIndexRouteImport.update({
  id: '/documentos/',
  path: '/documentos/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/configuracion/',
  path: '/configuracion/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIndexRoute = AppCasosIndexRouteImport.update({
  id: '/casos/',
  path: '/casos/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaIndexRoute = AppAgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => AppRoute,
} as any)
const ApiGoogleCalendarWebhookRoute =
  ApiGoogleCalendarWebhookRouteImport.update({
    id: '/api/google-calendar/webhook',
    path: '/api/google-calendar/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarSyncEventRoute =
  ApiGoogleCalendarSyncEventRouteImport.update({
    id: '/api/google-calendar/sync-event',
    path: '/api/google-calendar/sync-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarStatusRoute = ApiGoogleCalendarStatusRouteImport.update({
  id: '/api/google-calendar/status',
  path: '/api/google-calendar/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarConnectRoute =
  ApiGoogleCalendarConnectRouteImport.update({
    id: '/api/google-calendar/connect',
    path: '/api/google-calendar/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarActionsRoute =
  ApiGoogleCalendarActionsRouteImport.update({
    id: '/api/google-calendar/actions',
    path: '/api/google-calendar/actions',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppTareasTodasRoute = AppTareasTodasRouteImport.update({
  id: '/tareas/todas',
  path: '/tareas/todas',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasTableroRoute = AppTareasTableroRouteImport.update({
  id: '/tareas/tablero',
  path: '/tareas/tablero',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasProximasRoute = AppTareasProximasRouteImport.update({
  id: '/tareas/proximas',
  path: '/tareas/proximas',
  getParentRoute: () => AppRoute,
} as any)
const AppTareasMiasRoute = AppTareasMiasRouteImport.update({
  id: '/tareas/mias',
  path: '/tareas/mias',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIdRoute = AppClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCasosIdRoute = AppCasosIdRouteImport.update({
  id: '/casos/$id',
  path: '/casos/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/resonancia': typeof ResonanciaRoute
  '/casos/$id': typeof AppCasosIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/tareas/mias': typeof AppTareasMiasRoute
  '/tareas/proximas': typeof AppTareasProximasRoute
  '/tareas/tablero': typeof AppTareasTableroRoute
  '/tareas/todas': typeof AppTareasTodasRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/agenda/': typeof AppAgendaIndexRoute
  '/casos/': typeof AppCasosIndexRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
  '/documentos/': typeof AppDocumentosIndexRoute
  '/importaciones/': typeof AppImportacionesIndexRoute
  '/pagos/': typeof AppPagosIndexRoute
  '/reportes/': typeof AppReportesIndexRoute
  '/revision-ia/': typeof AppRevisionIaIndexRoute
  '/tareas/': typeof AppTareasIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/resonancia': typeof ResonanciaRoute
  '/': typeof AppIndexRoute
  '/casos/$id': typeof AppCasosIdRoute
  '/clientes/$id': typeof AppClientesIdRoute
  '/tareas/mias': typeof AppTareasMiasRoute
  '/tareas/proximas': typeof AppTareasProximasRoute
  '/tareas/tablero': typeof AppTareasTableroRoute
  '/tareas/todas': typeof AppTareasTodasRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/agenda': typeof AppAgendaIndexRoute
  '/casos': typeof AppCasosIndexRoute
  '/clientes': typeof AppClientesIndexRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
  '/documentos': typeof AppDocumentosIndexRoute
  '/importaciones': typeof AppImportacionesIndexRoute
  '/pagos': typeof AppPagosIndexRoute
  '/reportes': typeof AppReportesIndexRoute
  '/revision-ia': typeof AppRevisionIaIndexRoute
  '/tareas': typeof AppTareasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/resonancia': typeof ResonanciaRoute
  '/_app/': typeof AppIndexRoute
  '/_app/casos/$id': typeof AppCasosIdRoute
  '/_app/clientes/$id': typeof AppClientesIdRoute
  '/_app/tareas/mias': typeof AppTareasMiasRoute
  '/_app/tareas/proximas': typeof AppTareasProximasRoute
  '/_app/tareas/tablero': typeof AppTareasTableroRoute
  '/_app/tareas/todas': typeof AppTareasTodasRoute
  '/api/google-calendar/actions': typeof ApiGoogleCalendarActionsRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/connect': typeof ApiGoogleCalendarConnectRoute
  '/api/google-calendar/status': typeof ApiGoogleCalendarStatusRoute
  '/api/google-calendar/sync-event': typeof ApiGoogleCalendarSyncEventRoute
  '/api/google-calendar/webhook': typeof ApiGoogleCalendarWebhookRoute
  '/_app/agenda/': typeof AppAgendaIndexRoute
  '/_app/casos/': typeof AppCasosIndexRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
  '/_app/documentos/': typeof AppDocumentosIndexRoute
  '/_app/importaciones/': typeof AppImportacionesIndexRoute
  '/_app/pagos/': typeof AppPagosIndexRoute
  '/_app/reportes/': typeof AppReportesIndexRoute
  '/_app/revision-ia/': typeof AppRevisionIaIndexRoute
  '/_app/tareas/': typeof AppTareasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/resonancia'
    | '/casos/$id'
    | '/clientes/$id'
    | '/tareas/mias'
    | '/tareas/proximas'
    | '/tareas/tablero'
    | '/tareas/todas'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/agenda/'
    | '/casos/'
    | '/clientes/'
    | '/configuracion/'
    | '/documentos/'
    | '/importaciones/'
    | '/pagos/'
    | '/reportes/'
    | '/revision-ia/'
    | '/tareas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/resonancia'
    | '/'
    | '/casos/$id'
    | '/clientes/$id'
    | '/tareas/mias'
    | '/tareas/proximas'
    | '/tareas/tablero'
    | '/tareas/todas'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/agenda'
    | '/casos'
    | '/clientes'
    | '/configuracion'
    | '/documentos'
    | '/importaciones'
    | '/pagos'
    | '/reportes'
    | '/revision-ia'
    | '/tareas'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/resonancia'
    | '/_app/'
    | '/_app/casos/$id'
    | '/_app/clientes/$id'
    | '/_app/tareas/mias'
    | '/_app/tareas/proximas'
    | '/_app/tareas/tablero'
    | '/_app/tareas/todas'
    | '/api/google-calendar/actions'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/connect'
    | '/api/google-calendar/status'
    | '/api/google-calendar/sync-event'
    | '/api/google-calendar/webhook'
    | '/_app/agenda/'
    | '/_app/casos/'
    | '/_app/clientes/'
    | '/_app/configuracion/'
    | '/_app/documentos/'
    | '/_app/importaciones/'
    | '/_app/pagos/'
    | '/_app/reportes/'
    | '/_app/revision-ia/'
    | '/_app/tareas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResonanciaRoute: typeof ResonanciaRoute
  ApiGoogleCalendarActionsRoute: typeof ApiGoogleCalendarActionsRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarConnectRoute: typeof ApiGoogleCalendarConnectRoute
  ApiGoogleCalendarStatusRoute: typeof ApiGoogleCalendarStatusRoute
  ApiGoogleCalendarSyncEventRoute: typeof ApiGoogleCalendarSyncEventRoute
  ApiGoogleCalendarWebhookRoute: typeof ApiGoogleCalendarWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resonancia': {
      id: '/resonancia'
      path: '/resonancia'
      fullPath: '/resonancia'
      preLoaderRoute: typeof ResonanciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/': {
      id: '/_app/tareas/'
      path: '/tareas'
      fullPath: '/tareas/'
      preLoaderRoute: typeof AppTareasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/revision-ia/': {
      id: '/_app/revision-ia/'
      path: '/revision-ia'
      fullPath: '/revision-ia/'
      preLoaderRoute: typeof AppRevisionIaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reportes/': {
      id: '/_app/reportes/'
      path: '/reportes'
      fullPath: '/reportes/'
      preLoaderRoute: typeof AppReportesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pagos/': {
      id: '/_app/pagos/'
      path: '/pagos'
      fullPath: '/pagos/'
      preLoaderRoute: typeof AppPagosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importaciones/': {
      id: '/_app/importaciones/'
      path: '/importaciones'
      fullPath: '/importaciones/'
      preLoaderRoute: typeof AppImportacionesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos/': {
      id: '/_app/documentos/'
      path: '/documentos'
      fullPath: '/documentos/'
      preLoaderRoute: typeof AppDocumentosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/configuracion'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casos/': {
      id: '/_app/casos/'
      path: '/casos'
      fullPath: '/casos/'
      preLoaderRoute: typeof AppCasosIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agenda/': {
      id: '/_app/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AppAgendaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/google-calendar/webhook': {
      id: '/api/google-calendar/webhook'
      path: '/api/google-calendar/webhook'
      fullPath: '/api/google-calendar/webhook'
      preLoaderRoute: typeof ApiGoogleCalendarWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/sync-event': {
      id: '/api/google-calendar/sync-event'
      path: '/api/google-calendar/sync-event'
      fullPath: '/api/google-calendar/sync-event'
      preLoaderRoute: typeof ApiGoogleCalendarSyncEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/status': {
      id: '/api/google-calendar/status'
      path: '/api/google-calendar/status'
      fullPath: '/api/google-calendar/status'
      preLoaderRoute: typeof ApiGoogleCalendarStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/connect': {
      id: '/api/google-calendar/connect'
      path: '/api/google-calendar/connect'
      fullPath: '/api/google-calendar/connect'
      preLoaderRoute: typeof ApiGoogleCalendarConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/actions': {
      id: '/api/google-calendar/actions'
      path: '/api/google-calendar/actions'
      fullPath: '/api/google-calendar/actions'
      preLoaderRoute: typeof ApiGoogleCalendarActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tareas/todas': {
      id: '/_app/tareas/todas'
      path: '/tareas/todas'
      fullPath: '/tareas/todas'
      preLoaderRoute: typeof AppTareasTodasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/tablero': {
      id: '/_app/tareas/tablero'
      path: '/tareas/tablero'
      fullPath: '/tareas/tablero'
      preLoaderRoute: typeof AppTareasTableroRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/proximas': {
      id: '/_app/tareas/proximas'
      path: '/tareas/proximas'
      fullPath: '/tareas/proximas'
      preLoaderRoute: typeof AppTareasProximasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tareas/mias': {
      id: '/_app/tareas/mias'
      path: '/tareas/mias'
      fullPath: '/tareas/mias'
      preLoaderRoute: typeof AppTareasMiasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$id': {
      id: '/_app/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AppClientesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/casos/$id': {
      id: '/_app/casos/$id'
      path: '/casos/$id'
      fullPath: '/casos/$id'
      preLoaderRoute: typeof AppCasosIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppCasosIdRoute: typeof AppCasosIdRoute
  AppClientesIdRoute: typeof AppClientesIdRoute
  AppTareasMiasRoute: typeof AppTareasMiasRoute
  AppTareasProximasRoute: typeof AppTareasProximasRoute
  AppTareasTableroRoute: typeof AppTareasTableroRoute
  AppTareasTodasRoute: typeof AppTareasTodasRoute
  AppAgendaIndexRoute: typeof AppAgendaIndexRoute
  AppCasosIndexRoute: typeof AppCasosIndexRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
  AppDocumentosIndexRoute: typeof AppDocumentosIndexRoute
  AppImportacionesIndexRoute: typeof AppImportacionesIndexRoute
  AppPagosIndexRoute: typeof AppPagosIndexRoute
  AppReportesIndexRoute: typeof AppReportesIndexRoute
  AppRevisionIaIndexRoute: typeof AppRevisionIaIndexRoute
  AppTareasIndexRoute: typeof AppTareasIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppCasosIdRoute: AppCasosIdRoute,
  AppClientesIdRoute: AppClientesIdRoute,
  AppTareasMiasRoute: AppTareasMiasRoute,
  AppTareasProximasRoute: AppTareasProximasRoute,
  AppTareasTableroRoute: AppTareasTableroRoute,
  AppTareasTodasRoute: AppTareasTodasRoute,
  AppAgendaIndexRoute: AppAgendaIndexRoute,
  AppCasosIndexRoute: AppCasosIndexRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
  AppDocumentosIndexRoute: AppDocumentosIndexRoute,
  AppImportacionesIndexRoute: AppImportacionesIndexRoute,
  AppPagosIndexRoute: AppPagosIndexRoute,
  AppReportesIndexRoute: AppReportesIndexRoute,
  AppRevisionIaIndexRoute: AppRevisionIaIndexRoute,
  AppTareasIndexRoute: AppTareasIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResonanciaRoute: ResonanciaRoute,
  ApiGoogleCalendarActionsRoute: ApiGoogleCalendarActionsRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarConnectRoute: ApiGoogleCalendarConnectRoute,
  ApiGoogleCalendarStatusRoute: ApiGoogleCalendarStatusRoute,
  ApiGoogleCalendarSyncEventRoute: ApiGoogleCalendarSyncEventRoute,
  ApiGoogleCalendarWebhookRoute: ApiGoogleCalendarWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
